version: '3.8'
services:
  db:
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    env_file:
      - .env
  redis:
    image: redis
    ports:
      - '6379:6379'
    restart: always
